package com.lili.dao;

import com.lili.pojo.Cart;
import com.lili.pojo.Product;
import org.apache.ibatis.annotations.Param;

import java.util.List;


public interface ProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_product
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_product
     *
     * @mbg.generated
     */
    int insert(Product record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_product
     *
     * @mbg.generated
     */
    Product selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_product
     *
     * @mbg.generated
     */
    List<Product> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_product
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Product record);

    /**
     * 搜索商品
     */
    List<Product> findProductByNameAndId(@Param("productId") Integer productId,
                                         @Param("productName") String productName);

    /**
     * 扣库存
     * @param productId
     * @param stock
     * @return
     */
    int reduceProductStock(@Param("productId") Integer productId,
                           @Param("stock") Integer stock);

    /**
     * 前台页面查看最热商品
     * @param
     * @return
     */
    List<Product> findCategory(@Param("product") Product product);

}