package com.lili.dao;

import com.lili.common.ServerResponse;
import com.lili.pojo.User;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_user
     *
     * @mbg.generated
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_user
     *
     * @mbg.generated
     */
    User selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_user
     *
     * @mbg.generated
     */
    List<User> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(User record);

    /**
     * 判断用户名是否存在
     */
    int isExistUsername(@Param("username") String username);

    /**
     * 判断邮箱是否存在
     */
    int isExistEmail(@Param("email") String email);

    /**
     * 根据用户名和密码查询
     *
     */
    User isExistsByUsernameAndPassword(@Param("username") String username,
                                       @Param("password") String password);

    /**
     *根据username获取密保问题
     */
    String forgetGetQuestion(@Param("username") String username);

    /**
     * 校验答案接口
     */
    int forgetCheckAnswer(@Param("username")String username,
                          @Param("question") String question,
                          @Param("answer") String answer);

    /**
     * 重置密码接口
     */
    int forgetResetPassword(@Param("username") String username,
                            @Param("password") String password_new);

    /**
     * 修改用户信息
     */
    int updateUserByActivate(@Param("user") User user);
}